openapi: 3.0.3
info:
  title: Sample Yoga API
  version: 0.1.0
  description: Minimal API used by gpt-creator for scaffolding.
servers:
  - url: http://localhost:3000/api/v1
paths:
  /health:
    get:
      summary: Health check
      operationId: getHealth
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: Healthy
  /programs:
    get:
      summary: List programs
      operationId: listPrograms
      parameters:
        - name: type
          in: query
          description: Program type/category (e.g., yoga, pilates)
          schema: { type: string }
        - name: instructor
          in: query
          description: Instructor id
          schema: { type: string }
        - name: level
          in: query
          description: Level filter
          schema:
            type: string
            enum: [beginner, intermediate, advanced]
        - name: from
          in: query
          description: ISO datetime lower bound (inclusive)
          schema:
            type: string
            format: date-time
        - name: to
          in: query
          description: ISO datetime upper bound (inclusive)
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: A list of programs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Program'
              examples:
                sample:
                  value:
                    - id: 1
                      title: "Vinyasa Flow"
                      type: "yoga"
                      level: "beginner"
                      startDate: "2025-01-12T10:00:00Z"
                      instructorId: 101
                      instructor:
                        id: 101
                        name: "Aylin Kaya"
                        email: "aylin@example.com"
                    - id: 2
                      title: "Power Yoga"
                      type: "yoga"
                      level: "advanced"
                      startDate: "2025-01-12T18:00:00Z"
                      instructorId: 102
                      instructor:
                        id: 102
                        name: "Marco Rossi"
                        email: "marco@example.com"
components:
  schemas:
    Program:
      type: object
      required: [id, title, type, level, startDate]
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        type:
          type: string
          description: Domain/category (e.g., yoga, pilates, mindfulness)
        level:
          type: string
          enum: [beginner, intermediate, advanced]
        startDate:
          type: string
          format: date-time
        instructorId:
          type: integer
          format: int64
          nullable: true
        instructor:
          $ref: '#/components/schemas/Instructor'
    Instructor:
      type: object
      required: [id, name]
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
          format: email
