#!/usr/bin/env bash
# Auto-generated by gpt-creator CLI. Safe to replace during upgrades.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_root="$(cd "${script_dir}/.." && pwd)"

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

export CI="${CI:-1}"
export PNPM_DISABLE_SELF_UPDATE_CHECK=1
export PNPM_CONFIG_CONFIRM_MODULES_REMOVAL=false
export NPM_CONFIG_FUND=false
export NPM_CONFIG_AUDIT=false

cd "$project_root"

if [[ -d "node_modules" ]]; then
  chmod -R u+w "node_modules" 2>/dev/null || true
fi

if [[ -f "pnpm-lock.yaml" || -f "pnpm-workspace.yaml" ]]; then
  if command_exists pnpm; then
    pnpm install --recursive --frozen-lockfile --config.confirmModulesRemoval=false --reporter=silent || \
      pnpm install --config.confirmModulesRemoval=false --reporter=silent || true
    exit 0
  fi
fi

if [[ -f "package-lock.json" || -f "package.json" ]]; then
  if command_exists npm; then
    npm install --no-fund --no-audit --quiet || true
    exit 0
  fi
fi

if [[ -f "requirements.txt" ]]; then
  if command_exists pip3; then
    pip3 install -r requirements.txt || true
    exit 0
  elif command_exists pip; then
    pip install -r requirements.txt || true
    exit 0
  fi
fi

exit 0
